### ISSUE TITLE
Provide Browserified & Minified Code In Releases

### ISSUE THREAD

**Issue by xcthulhu** [bitpay/bitauth#44]
I recently wrote a Closure Extern File and made a cljsjs package for BitAuth: 
https://github.com/cljsjs/packages/pull/223

@crisptrutski suggested that I request upstream if you could put a copy of the browserified and minified code in your releases.

Thanks!

**Comment by crisptrutski** [comment]
@xcthulhu wouldn't be surprised if there's hesitance to accept this change - versioning `/dist` creates lots of noise and also inconvenience (eg. cannot checkout another branch if they're dirty)

Alternates:

1. Create tagged release commits (usually not on `master` itself), with artifacts versioned here only
2. Add the build artifacts manually to the Github release (see bottom of [this announcement](https://github.com/blog/1547-release-your-software))
3. Ensure there are some dependable, versioned CDN links to the artifacts

(3) is obviously the winner if it already exists (save schlepping)

**Comment by braydonf** [comment]
Yep, this has been discussed before. And including the browserified version in the master branch isn't desired, for the reasons mentioned by @crisptrutski

The current strategy is to tag release commits that include the browserified bundle and push to the git repository primarily for bower, since it's git based. That is at least how it's currently handled for all of the bitcore releases, as well as uploading compiled binaries to a CDN for bitcore-node, however we haven't updated the release process for bitauth yet. We've previously released builds via github releases: https://github.com/bitpay/bitauth/releases/tag/v0.1.2 however it looks like the latest two were not, unfortunately. I think option 1, in this case would be most applicable, as to work with bower.

**Comment by xcthulhu** [comment]
Cool, I'll go with whatever you guys decide to run with.

I just want to use this thing because the recent Ashley Madison stuff has reminded me that BitAuth is a great idea :D
