### ISSUE TITLE
Why not BitID?

### ISSUE THREAD

**Issue by apetersson** [bitpay/bitauth#9]
There is an existing proposal with working implementations (Darkwallet, Mycelium, mediawiki) . It would be great to give a motivation how BitAuth improves over BitID. This is not clear from the blogpost  https://github.com/bitid/bitid

**Comment by braydonf** [comment]
There should be compatibility between BitID and BitAuth, especially since it's using the same crypto. I think the only difference is that BitID uses a bitcoin address as the identifier and BitAuth uses a different version byte when encoding an "address" and thus isn't necessarily used to receive bitcoin.
